config/routes.rb
Rails.application.routes.draw do
  root "static#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :countries
  resources :languages
  resources :authors
  resources :books
  resources :chapters
  resources :paragraphs

end

app/models/paragraph.rb
class Paragraph < ApplicationRecord
  belongs_to :chapter
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_action :set_paragraph, only: [:show, :edit, :update, :destroy]

  # GET /paragraphs
  # GET /paragraphs.json
  def index
    @paragraphs = Paragraph.all
  end

  # GET /paragraphs/1
  # GET /paragraphs/1.json
  def show
  end

  # GET /paragraphs/new
  def new
    @paragraph = Paragraph.new
  end

  # GET /paragraphs/1/edit
  def edit
  end

  # POST /paragraphs
  # POST /paragraphs.json
  def create
    @paragraph = Paragraph.new(paragraph_params)

    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully created.' }
        format.json { render :show, status: :created, location: @paragraph }
      else
        format.html { render :new }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paragraphs/1
  # PATCH/PUT /paragraphs/1.json
  def update
    respond_to do |format|
      if @paragraph.update(paragraph_params)
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully updated.' }
        format.json { render :show, status: :ok, location: @paragraph }
      else
        format.html { render :edit }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragraphs/1
  # DELETE /paragraphs/1.json
  def destroy
    @paragraph.destroy
    respond_to do |format|
      format.html { redirect_to paragraphs_url, notice: 'Paragraph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paragraph_params
      params.require(:paragraph).permit(:body, :chapter_id)
    end
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/views/paragraphs/_form.html.erb
<%= form_with(model: paragraph, local: true) do |form| %>
  <% if paragraph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paragraph.errors.count, "error") %> prohibited this paragraph from being saved:</h2>

      <ul>
      <% paragraph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field form-group">
    <%= form.label :chapter_id %>
    <%= collection_select(:paragraph, :chapter_id, Chapter.all, :id, :title) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/paragraphs/edit.html.erb
<h1>Editing Paragraph</h1>

<%= render 'form', paragraph: @paragraph %>

<%= link_to 'Show', @paragraph %> |
<%= link_to 'Back', paragraphs_path %>

app/views/paragraphs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paragraphs</h1>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Body</th>
      <th>Chapter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paragraphs.each do |paragraph| %>
      <tr>
        <td><%= paragraph.body %></td>
        <td><%= paragraph.chapter_id %></td>
        <td><%= link_to 'Show', paragraph %></td>
        <td><%= link_to 'Edit', edit_paragraph_path(paragraph) %></td>
        <td><%= link_to 'Destroy', paragraph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paragraph', new_paragraph_path %>

app/views/paragraphs/new.html.erb
<h1>New Paragraph</h1>

<%= render 'form', paragraph: @paragraph %>

<%= link_to 'Back', paragraphs_path %>

app/views/paragraphs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @paragraph.body %>
</p>

<p>
  <strong>Chapter:</strong>
  <%= @paragraph.chapter_id %>
</p>

<%= link_to 'Edit', edit_paragraph_path(@paragraph) %> |
<%= link_to 'Back', paragraphs_path %>